use_frameworks!

platform :ios, '9.0'

target 'MBNetworkMonitor_Example' do
  pod 'MBNetworkMonitor', :path => '../'
  pod 'DoraemonKit/Core'
  pod 'Masonry'
  target 'MBNetworkMonitor_Tests' do
    inherit! :search_paths

    
  end
end
